# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Weimin Zhou
description: >- # this means to ignore newlines until "baseurl:"
  Econ Ph.D Candidate, Peking University HSBC Business School
baseurl: "/homepage" # the subpath of the site
url: "https://zhouweimin-econ.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-282664181-1"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: zhouweimin@stu.pku.edu.cn
      link: mailto:zhouweimin@stu.pku.edu.cn

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
